const CERT_URL="https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com";
type Claims={aud?:string;iss?:string;sub?:string;exp?:number;iat?:number;auth_time?:number;name?:string;email?:string;[k:string]:unknown};
let cache:{keys:Record<string,CryptoKey>;expiresAt:number}|null=null;
function b64urlBytes(input:string){const pad=input.length%4===0?"":"=".repeat(4-input.length%4);const s=input.replace(/-/g,"+").replace(/_/g,"/")+pad;const raw=atob(s);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
function b64json<T>(s:string){return JSON.parse(new TextDecoder().decode(b64urlBytes(s))) as T}
function pemToDer(pem:string){const b64=pem.replace(/-----BEGIN CERTIFICATE-----/g,"").replace(/-----END CERTIFICATE-----/g,"").replace(/\s+/g,"");const raw=atob(b64);return Uint8Array.from(raw,c=>c.charCodeAt(0)).buffer}
async function signingKeys(){const now=Date.now();if(cache&&cache.expiresAt>now+60000)return cache.keys;const r=await fetch(CERT_URL,{cf:{cacheTtl:3600}});if(!r.ok)throw new Error("Unable to retrieve Firebase signing keys.");const raw=await r.json() as Record<string,string>;const m=(r.headers.get("cache-control")??"").match(/max-age=(\d+)/);const maxAge=m?Number(m[1]):3600;const out:Record<string,CryptoKey>={};for(const[k,pem]of Object.entries(raw))out[k]=await crypto.subtle.importKey("spki",pemToDer(pem),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["verify"]);cache={keys:out,expiresAt:now+maxAge*1000};return out}
export async function verifyFirebaseIdToken(token:string,projectId:string){const p=token.split(".");if(p.length!==3)throw new Error("Invalid Firebase token.");const h=b64json<{alg?:string;kid?:string}>(p[0]);const c=b64json<Claims>(p[1]);const now=Math.floor(Date.now()/1000);if(h.alg!=="RS256"||!h.kid)throw new Error("Invalid Firebase header.");if(c.aud!==projectId)throw new Error("Invalid Firebase audience.");if(c.iss!==`https://securetoken.google.com/${projectId}`)throw new Error("Invalid Firebase issuer.");if(!c.sub||c.sub.length>256)throw new Error("Invalid Firebase subject.");if(typeof c.exp!=="number"||c.exp<=now)throw new Error("Firebase token expired.");if(typeof c.iat!=="number"||c.iat>now+60)throw new Error("Invalid Firebase issued-at.");if(typeof c.auth_time!=="number"||c.auth_time>now+60)throw new Error("Invalid Firebase auth time.");const key=(await signingKeys())[h.kid];if(!key)throw new Error("Unknown Firebase signing key.");const ok=await crypto.subtle.verify({name:"RSASSA-PKCS1-v1_5"},key,b64urlBytes(p[2]),new TextEncoder().encode(`${p[0]}.${p[1]}`));if(!ok)throw new Error("Invalid Firebase signature.");return{uid:c.sub!,claims:c}}
export async function requireAuth(request:Request,projectId:string){const h=request.headers.get("authorization")??"";if(!h.startsWith("Bearer "))throw new Response(JSON.stringify({message:"Authentication required."}),{status:401,headers:{"content-type":"application/json"}});try{return await verifyFirebaseIdToken(h.slice(7).trim(),projectId)}catch(e){throw new Response(JSON.stringify({message:e instanceof Error?e.message:"Invalid authentication."}),{status:401,headers:{"content-type":"application/json"}})}}
