import{Lobby}from"./lobby";import{GameRoom}from"./room";import{requireAuth}from"./auth";export{Lobby,GameRoom};export interface Env{GAME_ROOM:DurableObjectNamespace<GameRoom>;LOBBY:DurableObjectNamespace<Lobby>;FIREBASE_PROJECT_ID:string;ALLOWED_ORIGIN:string}
function cors(origin:string|null,allowed:string){return{"access-control-allow-origin":origin===allowed?origin:allowed,"access-control-allow-headers":"Authorization, Content-Type","access-control-allow-methods":"GET, POST, OPTIONS","vary":"Origin"}}
function out(data:any,status=200,req?:Request,env?:Env){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json",...cors(req?.headers.get("origin")??null,env?.ALLOWED_ORIGIN??"https://night-chamber.pages.dev")}})}
export default{async fetch(req:Request,env:Env){const u=new URL(req.url),origin=req.headers.get("origin");if(origin&&origin!==env.ALLOWED_ORIGIN)return new Response("Origin not allowed",{status:403});if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(origin,env.ALLOWED_ORIGIN)});if(u.pathname==="/api/health")return out({ok:true,version:"0.5.0",durableObjects:true},200,req,env);
let me:any;try{if(u.pathname.startsWith("/api/"))me=await requireAuth(req,env.FIREBASE_PROJECT_ID)}catch(e){if(e instanceof Response){const h=new Headers(e.headers);Object.entries(cors(origin,env.ALLOWED_ORIGIN)).forEach(([k,v])=>h.set(k,v));return new Response(await e.text(),{status:e.status,headers:h})}throw e}
const lobby=env.LOBBY.get(env.LOBBY.idFromName("global"));if(req.method==="POST"&&u.pathname==="/api/rooms"){const b=await req.json().catch(()=>({}));const r=await lobby.fetch(new Request("https://lobby/create",{method:"POST",body:JSON.stringify({...b,uid:me.uid}),headers:{"content-type":"application/json"}}));return new Response(await r.text(),{status:r.status,headers:{...cors(origin,env.ALLOWED_ORIGIN),"content-type":"application/json"}})}
if(req.method==="GET"&&u.pathname==="/api/rooms/public"){const r=await lobby.fetch(new Request("https://lobby/public"));return new Response(await r.text(),{status:r.status,headers:{...cors(origin,env.ALLOWED_ORIGIN),"content-type":"application/json"}})}
const info=u.pathname.match(/^\/api\/rooms\/([A-Z0-9]{4,12})$/);if(req.method==="GET"&&info){const r=await lobby.fetch(new Request(`https://lobby/room/${info[1]}`));return new Response(await r.text(),{status:r.status,headers:{...cors(origin,env.ALLOWED_ORIGIN),"content-type":"application/json"}})}
const join=u.pathname.match(/^\/api\/rooms\/([A-Z0-9]{4,12})\/join$/);if(req.method==="POST"&&join){const r=await lobby.fetch(new Request(`https://lobby/room/${join[1]}`));if(!r.ok)return new Response(await r.text(),{status:r.status,headers:cors(origin,env.ALLOWED_ORIGIN)});const room=await r.json() as any;if(room.players>=room.maxPlayers)return out({message:"Room full."},409,req,env);return out(room,200,req,env)}
const ws=u.pathname.match(/^\/ws\/([A-Z0-9]{4,12})$/);if(ws){const r=await lobby.fetch(new Request(`https://lobby/room/${ws[1]}`));if(!r.ok)return new Response("Room not found",{status:404});const room=await r.json() as any;if(room.players>=room.maxPlayers)return new Response("Room full",{status:409});const stub=env.GAME_ROOM.get(env.GAME_ROOM.idFromName(room.id));const r2=new Request(req);r2.headers.set("x-room-code",ws[1]);return stub.fetch(r2)}
return new Response("Night Chamber Worker v0.5.0")}}