import{Lobby}from"./lobby";import{GameRoom}from"./room";import{requireAuth}from"./auth";export{Lobby,GameRoom};
export interface Env{GAME_ROOM:DurableObjectNamespace<GameRoom>;LOBBY:DurableObjectNamespace<Lobby>;FIREBASE_PROJECT_ID:string;ALLOWED_ORIGIN:string}
const cors=(o:string|null,a:string)=>({"access-control-allow-origin":o===a?o:a,"access-control-allow-headers":"Authorization, Content-Type","access-control-allow-methods":"GET, POST, OPTIONS","access-control-max-age":"86400","vary":"Origin"});
function withCors(r:Response,req:Request,env:Env){const h=new Headers(r.headers);for(const[k,v]of Object.entries(cors(req.headers.get("origin"),env.ALLOWED_ORIGIN)))h.set(k,v);return new Response(r.body,{status:r.status,statusText:r.statusText,headers:h})}
export default{async fetch(req:Request,env:Env){const u=new URL(req.url),origin=req.headers.get("origin");if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(origin,env.ALLOWED_ORIGIN)});if(origin&&origin!==env.ALLOWED_ORIGIN)return new Response(JSON.stringify({ok:false,message:"Origin not allowed."}),{status:403,headers:{"content-type":"application/json",...cors(origin,env.ALLOWED_ORIGIN)}});if(u.pathname==="/api/health")return Response.json({ok:true,version:"1.2.0",service:"night-chamber-worker",durableObjects:true});
let auth:any=null;if(u.pathname.startsWith("/api/")){const a=await requireAuth(req,env.FIREBASE_PROJECT_ID);if(a instanceof Response)return withCors(a,req,env);auth=a}
try{const lobby=env.LOBBY.get(env.LOBBY.idFromName("global"));
if(req.method==="POST"&&u.pathname==="/api/rooms"){const b=await req.json().catch(()=>({}));return withCors(await lobby.fetch(new Request("https://lobby/create",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...b,uid:auth.uid})})),req,env)}
if(req.method==="GET"&&u.pathname==="/api/rooms/public")return withCors(await lobby.fetch(new Request("https://lobby/public")),req,env);
const info=u.pathname.match(/^\/api\/rooms\/([A-Z0-9]{6})$/);if(req.method==="GET"&&info)return withCors(await lobby.fetch(new Request("https://lobby/room/"+info[1])),req,env);
const join=u.pathname.match(/^\/api\/rooms\/([A-Z0-9]{6})\/join$/);if(req.method==="POST"&&join){const r=await lobby.fetch(new Request("https://lobby/room/"+join[1]));if(!r.ok)return withCors(r,req,env);const d=await r.json() as any;if(!d.room)return new Response(JSON.stringify({ok:false,message:"Room data unavailable."}),{status:500,headers:{"content-type":"application/json",...cors(origin,env.ALLOWED_ORIGIN)}});if(d.room.status==="finished")return new Response(JSON.stringify({ok:false,message:"Match finished."}),{status:409,headers:{"content-type":"application/json",...cors(origin,env.ALLOWED_ORIGIN)}});if(d.room.players>=d.room.maxPlayers)return new Response(JSON.stringify({ok:false,message:"Room is full."}),{status:409,headers:{"content-type":"application/json",...cors(origin,env.ALLOWED_ORIGIN)}});return new Response(JSON.stringify(d.room),{status:200,headers:{"content-type":"application/json",...cors(origin,env.ALLOWED_ORIGIN)}})}
const ws=u.pathname.match(/^\/ws\/([A-Z0-9]{6})$/);if(ws){if(req.headers.get("Upgrade")!=="websocket")return new Response("WebSocket upgrade required",{status:426});const r=await lobby.fetch(new Request("https://lobby/room/"+ws[1]));if(!r.ok)return withCors(r,req,env);const d=await r.json() as any;if(!d.room)return new Response("Room unavailable",{status:404});if(d.room.players>=d.room.maxPlayers)return new Response("Room full",{status:409});const stub=env.GAME_ROOM.get(env.GAME_ROOM.idFromName(d.room.id));const f=new Request(req);f.headers.set("x-room-code",ws[1]);return stub.fetch(f)}
return new Response("Night Chamber Worker 1.2.0")}catch(e){return withCors(new Response(JSON.stringify({ok:false,message:e instanceof Error?e.message:"Internal server error."}),{status:500,headers:{"content-type":"application/json"}}),req,env)}}}
