import{Lobby}from"./lobby";import{GameRoom}from"./room";import{requireAuth}from"./auth";export{Lobby,GameRoom};
export interface Env{GAME_ROOM:DurableObjectNamespace<GameRoom>;LOBBY:DurableObjectNamespace<Lobby>;FIREBASE_PROJECT_ID:string;ALLOWED_ORIGIN:string}
const cors=(o:string|null,a:string)=>({"access-control-allow-origin":o===a?o:a,"access-control-allow-headers":"Authorization, Content-Type","access-control-allow-methods":"GET, POST, OPTIONS","vary":"Origin"});
const json=(d:unknown,s=200,r?:Request,e?:Env)=>Response.json(d,{status:s,headers:cors(r?.headers.get("origin")??null,e?.ALLOWED_ORIGIN??"https://night-chamber.pages.dev")});
async function getRoom(env:Env,code:string){return env.LOBBY.get(env.LOBBY.idFromName("global")).fetch(new Request(`https://lobby/room/${code}`))}
export default{async fetch(request:Request,env:Env){const u=new URL(request.url),o=request.headers.get("origin");if(o&&o!==env.ALLOWED_ORIGIN)return new Response("Origin not allowed",{status:403});if(request.method==="OPTIONS")return new Response(null,{status:204,headers:cors(o,env.ALLOWED_ORIGIN)});
 if(u.pathname==="/api/health")return json({ok:true,service:"night-chamber-worker",version:"0.4.0",durableObjects:true},200,request,env);
 let me:{uid:string;claims:Record<string,unknown>}|null=null;
 if(u.pathname.startsWith("/api/")){try{me=await requireAuth(request,env.FIREBASE_PROJECT_ID)}catch(res){if(res instanceof Response){const h=new Headers(res.headers);Object.entries(cors(o,env.ALLOWED_ORIGIN)).forEach(([k,v])=>h.set(k,v));return new Response(await res.text(),{status:res.status,headers:h})}throw res}}
 if(request.method==="POST"&&u.pathname==="/api/rooms"){const b=await request.json().catch(()=>({})) as any;const r=await env.LOBBY.get(env.LOBBY.idFromName("global")).fetch(new Request("https://lobby/create",{method:"POST",body:JSON.stringify({uid:me!.uid,mode:b.mode,visibility:b.visibility}),headers:{"content-type":"application/json"}}));return new Response(await r.text(),{status:r.status,headers:cors(o,env.ALLOWED_ORIGIN)})}
 if(request.method==="GET"&&u.pathname==="/api/rooms/public"){const r=await env.LOBBY.get(env.LOBBY.idFromName("global")).fetch(new Request("https://lobby/public"));return new Response(await r.text(),{status:r.status,headers:cors(o,env.ALLOWED_ORIGIN)})}
 const info=u.pathname.match(/^\/api\/rooms\/([A-Z0-9]{4,12})$/);if(request.method==="GET"&&info){const r=await getRoom(env,info[1]);return new Response(await r.text(),{status:r.status,headers:cors(o,env.ALLOWED_ORIGIN)})}
 const join=u.pathname.match(/^\/api\/rooms\/([A-Z0-9]{4,12})\/join$/);if(request.method==="POST"&&join){const r=await getRoom(env,join[1]);if(!r.ok)return new Response(await r.text(),{status:r.status,headers:cors(o,env.ALLOWED_ORIGIN)});const room=await r.json() as any;if(room.status!=="waiting"||room.players>=room.maxPlayers)return json({message:"Room unavailable."},409,request,env);return json(room,200,request,env)}
 const ws=u.pathname.match(/^\/ws\/([A-Z0-9]{4,12})$/);if(ws){const r=await getRoom(env,ws[1]);if(!r.ok)return new Response("Room not found.",{status:404});const room=await r.json() as any;const stub=env.GAME_ROOM.get(env.GAME_ROOM.idFromName(room.id));const proxied=new Request(request);proxied.headers.set("x-room-code",ws[1]);return stub.fetch(proxied)}
 return new Response("Night Chamber Worker 0.4.0")}}
