import{DurableObject}from"cloudflare:workers";
export class Lobby extends DurableObject{
 constructor(ctx:DurableObjectState,env:unknown){super(ctx,env);this.ctx.blockConcurrencyWhile(async()=>{this.ctx.storage.sql.exec(`CREATE TABLE IF NOT EXISTS rooms(code TEXT PRIMARY KEY,id TEXT NOT NULL,mode TEXT NOT NULL,visibility TEXT NOT NULL,max_players INTEGER NOT NULL,players INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'waiting',host_uid TEXT NOT NULL,created_at INTEGER NOT NULL)`);})}
 async fetch(request:Request){const u=new URL(request.url);
  if(request.method==="POST"&&u.pathname==="/create"){const b=await request.json() as any;if(!b.uid)return Response.json({message:"Missing user."},{status:400});const mode=b.mode==="2v2"||b.mode==="4v4"?b.mode:"1v1",visibility=b.visibility==="public"?"public":"private";let code="";for(let i=0;i<10;i++){const c=randomCode();if(!this.ctx.storage.sql.exec("SELECT code FROM rooms WHERE code=?",c).one()){code=c;break}}if(!code)return Response.json({message:"Could not allocate room."},{status:503});const id=crypto.randomUUID(),maxPlayers=mode==="1v1"?2:mode==="2v2"?4:8;this.ctx.storage.sql.exec("INSERT INTO rooms VALUES(?,?,?,?,?,?,?,?,?)",code,id,mode,visibility,maxPlayers,0,"waiting",b.uid,Date.now());return Response.json({code,id,mode,visibility,maxPlayers})}
  if(request.method==="POST"&&u.pathname==="/adjust"){const b=await request.json() as any;const code=String(b.code??"").toUpperCase(),delta=Math.max(-8,Math.min(8,Number(b.delta??0)));const row=this.ctx.storage.sql.exec("SELECT players,max_players as maxPlayers FROM rooms WHERE code=?",code).one() as any;if(!row)return Response.json({message:"Room not found."},{status:404});const n=Math.max(0,Math.min(Number(row.maxPlayers),Number(row.players)+delta));const status=n>=2?"playing":"waiting";this.ctx.storage.sql.exec("UPDATE rooms SET players=?,status=? WHERE code=?",n,status,code);return Response.json({players:n,status})}
  if(request.method==="GET"&&u.pathname==="/public"){return Response.json({rooms:this.ctx.storage.sql.exec("SELECT code,id,mode,visibility,max_players as maxPlayers,players,status FROM rooms WHERE visibility='public' AND status='waiting' ORDER BY created_at DESC LIMIT 30").toArray()})}
  if(request.method==="GET"&&u.pathname.startsWith("/room/")){const code=u.pathname.split("/")[2]?.toUpperCase(),row=this.ctx.storage.sql.exec("SELECT code,id,mode,visibility,max_players as maxPlayers,players,status FROM rooms WHERE code=?",code).one();if(!row)return Response.json({message:"Room not found."},{status:404});return Response.json(row)}
  return new Response("Not found",{status:404})
 }}
function randomCode(){const a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",b=new Uint8Array(6);crypto.getRandomValues(b);return Array.from(b,x=>a[x%a.length]).join("")}
