import{DurableObject}from"cloudflare:workers";import{GameEngine,Mode}from"./game";import{verifyFirebaseIdToken}from"./auth";
type Env={FIREBASE_PROJECT_ID:string;LOBBY:DurableObjectNamespace};type Identity={uid:string;username:string};
export class GameRoom extends DurableObject<Env>{
 private engine:GameEngine|null=null;private mode:Mode="1v1";private authed=new Map<WebSocket,Identity>();private roomCode:string|null=null;
 constructor(ctx:DurableObjectState,env:Env){super(ctx,env);this.ctx.blockConcurrencyWhile(async()=>{const m=await this.ctx.storage.get<Mode>("mode");this.mode=m??"1v1";this.engine=new GameEngine(this.mode);const saved=await this.ctx.storage.get<any>("game");if(saved&&saved.mode===this.mode)this.engine.restore(saved);this.roomCode=await this.ctx.storage.get<string>("roomCode")??null;for(const ws of this.ctx.getWebSockets()){const a=ws.deserializeAttachment() as any;if(a?.state==="authenticated"&&a.uid){this.authed.set(ws,{uid:a.uid,username:String(a.username??a.uid)});}}})}
 private lobby(){return this.env.LOBBY.get(this.env.LOBBY.idFromName("global"))}
 private async adjust(delta:number){if(!this.roomCode)return;await this.lobby().fetch(new Request("https://lobby/adjust",{method:"POST",body:JSON.stringify({code:this.roomCode,delta}),headers:{"content-type":"application/json"}}))}
 private async save(){if(this.engine)await this.ctx.storage.put("game",this.engine.serialize())}
 private broadcastStates(){for(const[ws,id]of this.authed){try{ws.send(JSON.stringify({type:"state",snapshot:this.engine?.snapshotFor(id.uid)}))}catch{}}}
 async fetch(request:Request){const incoming=request.headers.get("x-room-code");if(incoming)await this.ctx.storage.put("roomCode",incoming);if(incoming)this.roomCode=incoming;if(request.headers.get("Upgrade")!=="websocket")return Response.json({ok:true,mode:this.mode});const pair=new WebSocketPair();const[client,server]=Object.values(pair);this.ctx.acceptWebSocket(server);server.serializeAttachment({state:"unauthenticated"});server.send(JSON.stringify({type:"connected"}));return new Response(null,{status:101,webSocket:client})}
 async webSocketMessage(ws:WebSocket,message:string|ArrayBuffer){if(typeof message!=="string"||message.length>8192){ws.close(1009,"Message too large.");return}let d:any;try{d=JSON.parse(message)}catch{ws.send(JSON.stringify({type:"error",message:"Invalid JSON."}));return}const current=this.authed.get(ws);
  if(!current){if(d.type!=="auth"||typeof d.token!=="string"){ws.close(1008,"Authentication required.");return}try{const v=await verifyFirebaseIdToken(d.token,this.env.FIREBASE_PROJECT_ID);const username=String(v.claims.name??v.claims.email??v.uid).slice(0,40);let added=false;await this.ctx.blockConcurrencyWhile(async()=>{if(!this.engine)this.engine=new GameEngine(this.mode);added=this.engine.addPlayer(v.uid,username);await this.ctx.storage.put("mode",this.mode);await this.save()});this.authed.set(ws,{uid:v.uid,username});ws.serializeAttachment({state:"authenticated",uid:v.uid,username});if(added)await this.adjust(1);ws.send(JSON.stringify({type:"authenticated",uid:v.uid,snapshot:this.engine?.snapshotFor(v.uid)}));this.broadcastStates()}catch(e){ws.send(JSON.stringify({type:"error",message:e instanceof Error?e.message:"Authentication failed."}));ws.close(1008,"Authentication failed.")}return}
  try{let privateMessage:string|undefined;await this.ctx.blockConcurrencyWhile(async()=>{if(!this.engine)this.engine=new GameEngine(this.mode);if(d.type==="start")this.engine.start();else if(d.type==="fire"){if(typeof d.target!=="string")throw new Error("Invalid target.");this.engine.fire(current.uid,d.target)}else if(d.type==="use_item"){if(typeof d.itemId!=="string")throw new Error("Invalid item.");privateMessage=this.engine.useItem(current.uid,d.itemId).privateMessage}else if(d.type==="ping"){ws.send(JSON.stringify({type:"pong"}));return}else throw new Error("Unknown action.");await this.save()});if(privateMessage)ws.send(JSON.stringify({type:"private",message:privateMessage}));this.broadcastStates()}catch(e){ws.send(JSON.stringify({type:"error",message:e instanceof Error?e.message:"Action failed."}))}}
 async webSocketClose(ws:WebSocket){const id=this.authed.get(ws);this.authed.delete(ws);if(id&&this.engine){this.engine.removePlayer(id.uid);await this.save();await this.adjust(-1);this.broadcastStates()}}
 async webSocketError(ws:WebSocket){const id=this.authed.get(ws);this.authed.delete(ws);if(id&&this.engine){this.engine.removePlayer(id.uid);await this.save();await this.adjust(-1);this.broadcastStates()}}
}
