import{DurableObject}from"cloudflare:workers";import{Game,Mode}from"./game";import{verify}from"./auth";
type Env={FIREBASE_PROJECT_ID:string;LOBBY:DurableObjectNamespace};export class GameRoom extends DurableObject<Env>{private g:Game|null=null;private mode:Mode="1v1";private code="";private users=new Map<WebSocket,{uid:string;name:string}>();
constructor(ctx:DurableObjectState,env:Env){super(ctx,env);this.ctx.blockConcurrencyWhile(async()=>{this.mode=(await this.ctx.storage.get<Mode>("mode"))??"1v1";this.code=(await this.ctx.storage.get<string>("code"))??"";this.g=new Game(this.mode);const saved=await this.ctx.storage.get<any>("game");if(saved)this.g.restore(saved);for(const ws of this.ctx.getWebSockets()){const a=ws.deserializeAttachment() as any;if(a?.uid)this.users.set(ws,{uid:a.uid,name:a.name})}})}
async fetch(req:Request){if(req.headers.get("Upgrade")!=="websocket")return Response.json({ok:true,mode:this.mode});this.code=req.headers.get("x-room-code")||this.code;await this.ctx.storage.put("code",this.code);const pair=new WebSocketPair(),[client,server]=Object.values(pair);this.ctx.acceptWebSocket(server);server.serializeAttachment({state:"unauthenticated"});return new Response(null,{status:101,webSocket:client})}
async adjust(delta:number){if(!this.code)return;await this.env.LOBBY.get(this.env.LOBBY.idFromName("global")).fetch(new Request("https://lobby/adjust",{method:"POST",body:JSON.stringify({code:this.code,delta}),headers:{"content-type":"application/json"}}))}
sendAll(){for(const[ws,u]of this.users)ws.send(JSON.stringify({type:"state",snapshot:this.g!.snapshot(u.uid)}))}
async save(){await this.ctx.storage.put("game",this.g!.save());await this.ctx.storage.put("mode",this.mode)}
async webSocketMessage(ws:WebSocket,data:string|ArrayBuffer){if(typeof data!=="string"||data.length>10000)return ws.close(1009,"Too large");let m:any;try{m=JSON.parse(data)}catch{return ws.send(JSON.stringify({type:"error",message:"Bad JSON"}))}const u=this.users.get(ws);
if(!u){if(m.type!=="auth")return ws.close(1008,"Auth required");try{const v=await verify(String(m.token),this.env.FIREBASE_PROJECT_ID),name=String(v.claims.name||v.claims.email||v.uid).slice(0,30);this.g!.add(v.uid,name);this.users.set(ws,{uid:v.uid,name});ws.serializeAttachment({uid:v.uid,name});await this.adjust(1);await this.save();ws.send(JSON.stringify({type:"authenticated",snapshot:this.g!.snapshot(v.uid)}));this.sendAll()}catch(e){ws.send(JSON.stringify({type:"error",message:e instanceof Error?e.message:"Auth failed"}));ws.close(1008,"Auth failed")}return}
try{let priv:string|undefined;if(m.type==="start")this.g!.start();else if(m.type==="fire")this.g!.fire(u.uid,String(m.target));else if(m.type==="use_item")priv=this.g!.use(u.uid,String(m.itemId)).private;else if(m.type==="ping")return ws.send(JSON.stringify({type:"pong"}));else throw Error("Unknown action");await this.save();if(priv)ws.send(JSON.stringify({type:"private",message:priv}));this.sendAll()}catch(e){ws.send(JSON.stringify({type:"error",message:e instanceof Error?e.message:"Action failed"}))}}
async webSocketClose(ws:WebSocket){const u=this.users.get(ws);this.users.delete(ws);if(u){this.g!.remove(u.uid);await this.save();await this.adjust(-1);this.sendAll()}}
async webSocketError(ws:WebSocket){return this.webSocketClose(ws)}}